version: '3'

tasks:
  get_chat_logs:
    generates: [dataset]
    cmds:
      - python3 dump.py >> tmp
      - cat dataset tmp | sort -u > tmp_dataset
      - mv tmp_dataset dataset
      - rm tmp

  train:
    deps: [get_chat_logs]
    sources: [dataset]
    generates: [model.json]
    cmds:
      - python quotes_generator/main.py train --dataset dataset --model model.json

  commit:
    - venv/Scripts/pip freeze > requirements.txt
    - cmd: git add .
      ignore_error: true
    - git status
    - cmd: git commit -m "Autocommit"
      ignore_error: true

  push_heroku:
    - git push heroku master

  push_github:
    - git push github master

  push:
    deps:
      - push_heroku
      - push_github

  deploy-fix:
    - task: commit
    - task: push

  deploy:
    - task: train
    - task: deploy-fix

