version: '3'

tasks:
  train:
    dir: quotes_generator
    sources: [quotes_generator/dataset]
    generates: [quotes_generator/model.json]
    cmds:
      - python3 main.py train

  commit:
    deps: [train]
    cmds:
      - git add *
      - git status
      - git commit -m "Autocommit"

  deploy:
    deps: [commit]
    cmds:
      - git push heroku master

