version: '3'

tasks:
  train:
    dir: quotes_generator
    cmds:
      - python3 main.py train

  commit:
    depends: [train]
    cmds:
      - git add *
      - git status
      - git commit -m "Autocommit"

  deploy:
    depends: [commit]
    cmds:
      - git push heroku master

