name: Push docker image to github registry

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag twitch-bot:${{ steps.date.outputs.date }}
    - uses: docker/login-action@v2.1.0
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: twitch-bot:${{ steps.date.outputs.date }}
        github-token: ${{ github.token }}
