name: Push docker image to github registry

on:
  push:
    branches: [ "master" ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
    - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag twitch-bot:${{ steps.date.outputs.date }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: twitch-bot:${{ steps.date.outputs.date }}
#     - uses: docker/login-action@v2.1.0
#       with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ github.token }}
#     - uses: docker/build-push-action@v3.2.0
#       with:
#         context: .
#         file: Dockerfile
#         push: true
#         tags: twitch-bot:${{ steps.date.outputs.date }}
#         github-token: ${{ github.token }}
        
